version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-test-container
    ports:
      - 3305:3306
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: 1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql:/var/lib/mysql
